apiVersion: v1
kind: ConfigMap
metadata:
  name: voyage-config
  namespace: voyage-analytics
data:
  MLFLOW_TRACKING_URI: "http://voyage-mlflow-service:5001"
  MODEL_DIR: "/app/outputs/models"
  DATA_DIR: "/app/data/raw"
  FLASK_ENV: "production"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voyage-ingress
  namespace: voyage-analytics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: voyage-analytics.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: voyage-api-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voyage-streamlit-service
                port:
                  number: 80
